"""PowerPoint Compiler - Compiles agent results into PowerPoint files."""
import io
from typing import Dict, Any, List
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.dml.color import RGBColor
import logging

logger = logging.getLogger(__name__)


class PPTCompiler:
    """Compiles agent outputs into PowerPoint presentations."""
    
    # Slide layout indices
    TITLE_SLIDE = 0
    TITLE_AND_CONTENT = 1
    BLANK = 6
    
    def compile(
        self,
        structure: Dict[str, Any],
        data: List[Dict[str, Any]],
        styling: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Compile all components into a PowerPoint presentation."""
        
        try:
            prs = Presentation()
            
            # Apply styling
            slide_master = styling.get("slide_master", {})
            color_scheme = styling.get("color_scheme", ["#4472C4", "#ED7D31", "#A5A5A5"])
            
            # Get slides configuration
            slides_config = structure.get("slides", [])
            
            # Create title slide
            title_slide_layout = prs.slide_layouts[self.TITLE_SLIDE]
            title_slide = prs.slides.add_slide(title_slide_layout)
            title = structure.get("title", "Presentation")
            subtitle = "Generated by AI Office Suite"
            
            title_slide.shapes.title.text = title
            if title_slide.placeholders[1]:
                title_slide.placeholders[1].text = subtitle
            
            # Create content slides
            for slide_config in slides_config:
                slide_type = slide_config.get("type", "content")
                
                if slide_type == "title":
                    continue  # Already created
                
                elif slide_type == "content":
                    self._add_content_slide(prs, slide_config, slide_master, color_scheme)
                
                elif slide_type == "data":
                    self._add_data_slide(prs, slide_config, data, slide_master, color_scheme)
                
                else:
                    self._add_content_slide(prs, slide_config, slide_master, color_scheme)
            
            # Add thank you slide
            thank_you_layout = prs.slide_layouts[self.TITLE_AND_CONTENT]
            thank_you_slide = prs.slides.add_slide(thank_you_layout)
            thank_you_slide.shapes.title.text = "Thank You"
            thank_you_slide.placeholders[1].text = "Questions?"
            
            # Save to bytes
            output = io.BytesIO()
            prs.save(output)
            output.seek(0)
            
            return {
                "content": output.getvalue(),
                "filename": "generated_presentation.pptx",
                "mime_type": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                "size": len(output.getvalue())
            }
            
        except Exception as e:
            logger.error(f"PowerPoint compilation failed: {e}")
            return self._create_fallback_output()
    
    def _add_content_slide(
        self,
        prs: Presentation,
        slide_config: Dict[str, Any],
        slide_master: Dict[str, Any],
        color_scheme: List[str]
    ):
        """Add a content slide to the presentation."""
        
        layout = prs.slide_layouts[self.TITLE_AND_CONTENT]
        slide = prs.slides.add_slide(layout)
        
        # Set title
        title = slide_config.get("title", "")
        slide.shapes.title.text = title
        
        # Apply title styling
        title_shape = slide.shapes.title
        title_frame = title_shape.text_frame
        title_para = title_frame.paragraphs[0]
        title_para.font.size = Pt(slide_master.get("title_font", {}).get("size", 44))
        title_para.font.bold = slide_master.get("title_font", {}).get("bold", True)
        title_para.font.name = slide_master.get("title_font", {}).get("name", "Calibri")
        
        # Set content
        content = slide_config.get("content", [])
        if isinstance(content, str):
            content = [content]
        
        body_shape = slide.placeholders[1]
        text_frame = body_shape.text_frame
        text_frame.clear()
        
        for i, text in enumerate(content):
            if i == 0:
                p = text_frame.paragraphs[0]
            else:
                p = text_frame.add_paragraph()
            
            p.text = str(text)
            p.level = 0
            p.font.size = Pt(slide_master.get("body_font", {}).get("size", 18))
            p.font.name = slide_master.get("body_font", {}).get("name", "Calibri")
    
    def _add_data_slide(
        self,
        prs: Presentation,
        slide_config: Dict[str, Any],
        data: List[Dict[str, Any]],
        slide_master: Dict[str, Any],
        color_scheme: List[str]
    ):
        """Add a data/chart slide to the presentation."""
        
        layout = prs.slide_layouts[self.TITLE_AND_CONTENT]
        slide = prs.slides.add_slide(layout)
        
        # Set title
        title = slide_config.get("title", "Data")
        slide.shapes.title.text = title
        
        # Add simple data summary
        if data:
            summary = f"Dataset contains {len(data)} records"
            body_shape = slide.placeholders[1]
            body_shape.text = summary
    
    def _create_fallback_output(self) -> Dict[str, Any]:
        """Create a minimal fallback PowerPoint."""
        prs = Presentation()
        
        title_slide_layout = prs.slide_layouts[self.TITLE_SLIDE]
        slide = prs.slides.add_slide(title_slide_layout)
        slide.shapes.title.text = "Generation Error"
        slide.placeholders[1].text = "There was an error generating your presentation"
        
        output = io.BytesIO()
        prs.save(output)
        output.seek(0)
        
        return {
            "content": output.getvalue(),
            "filename": "error.pptx",
            "mime_type": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
            "size": len(output.getvalue())
        }


# Global instance
ppt_compiler = PPTCompiler()
